### ISSUE TITLE
Support ExtractTextWebpackPlugin

### ISSUE THREAD

**Issue by eirikurn** [mozilla-neutrino/webpack-chain#20]
[This plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) has two interconnected config entries. A standard plugin, and a special module loader:

```javascript
{
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        }),
      },
    ],
  },
}
```

Behind the scenes, this `extract` function returns an array of loaders, specially formatted like so:

```javascript
use: [
  { loader: 'extract-text-webpack-plugin/loader', options: { omit: 1, remove: true } },
  { loader: 'style-loader' },
  { loader: 'css-loader' },
]
```

Not sure why they don't document this api for loader syntax consistency. In any case, `ExtractTextPlugin.extract` doesn't work well with how `webpack-chain` currently abstracts loaders in `Rule` and `ChainedMap`.

I'm not convinced that `webpack-chain`'s design should accommodate this pattern. Instead I'd suggest testing and documenting how to make it work with `.merge()` like so:

```javascript
config.module.rule('style')
  .test(/\.css$/)
  .merge({
    use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: 'css-loader',
    }),
  })
```

I haven't had time to verify this but I imagine this should work, even though the uses get their names from array indices: '0', '1', '2'.

Does this make sense. Where could this be documented?

**Comment by eliperelman** [comment]
Maybe add a section to the bottom of the readme showing this example.

**Comment by edmorley** [comment]
The way Neutrino 8 (which is based on webpack 3) did this, is:
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.2.3/packages/style-loader/index.js#L108-L120

However with webpack 4 `extract-text-webpack-plugin` is not supported, and its replacement [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) doesn't need the nested configuration:
https://github.com/mozilla-neutrino/neutrino-dev/blob/7b9b39119e1bb7c91a989a7bfb12a8d673d80661/packages/style-loader/index.js#L52

If someone wanted to open a PR to somehow document the `extract-text-webpack-plugin` case to the README under a "gotchas" or "common pitfalls" type section, I wouldn't object - but at this point it may not be worth it any more :-)

**Comment by edmorley** [comment]
Closing this for now given webpack 4 makes this plugin redundant.
