### ISSUE TITLE
clarify plugin docs

### ISSUE THREAD

**Issue by SeeThruHead** [mozilla-neutrino/webpack-chain#24]
i wanted to add webpack-manifest-plugin and was only able to do so via trial and error by adding an empty array as the second arg.

What does this arg do? How can I help to improve the docs?

```
    neutrino.config.plugin('manifest')
      .use(ManifestPlugin, [], { filename: 'manifest.json' });
```

**Comment by eliperelman** [comment]
According to the docs, https://github.com/mozilla-neutrino/webpack-chain#config-plugins-adding

```js
config
  .plugin(name)
  .use(WebpackPlugin, args)
```

You provide a plugin name, and `.use` takes the plugin, and the second argument is `args`, or an array of all the args that will be passed to the plugin on instantiation. In the case of this `ManifestPlugin`, it accepts an object as its only argument, so the `args` array just needs a single object:

```js
neutrino.config
  .plugin('manifest')
  .use(ManifestPlugin, [{ filename: 'manifest.json' }]);
```

If you want to create a PR to make the wording clearer, I would be happy to have it!
