### ISSUE TITLE
Alternative to `test()` metod

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/webpack-chain#35]
`test()` method defines expressions tested over files . In `webpack-chain` this method can be only overridden but can't be extended if its value is an array.

What if we add an alternative method that will be dedicated exactly to extensions and will support ChainedSet interface? Example

```js
config.module
    .rule('scripts')
        .extensions
            .add('js')
            .add('jsx')
            .merge([...])
            .end()
        .use('babel')
            .loader('babel-loader');
```
This collection can be converted to RegExp just before it is formatted for Webpack compilation.

Pros:
1. Better API to write middlewares
2. Extensions of any rule can be extracted and used for other purposes. May be very useful when call linter tools in CLI with the same extensions as a target.

I would even suggest to completely replace `test()` method as it will simplify the implementation.

**Comment by eliperelman** [comment]
The problem with this approach is that a RegExp for `.test` isn't just additive of extensions, it can do some pretty complex things. I don't think there is any way we could support both syntaxes and having them merged together into a single RegExp that webpack could understand. I also want to avoid adding custom methods that don't map well 1:1 with a webpack configuration as this opens the potential for conflicts in the future.

I'm going to close this without an intention to implement, but I would be happy to review a PR that demonstrates this is possible without conflict and covers all use cases.
