### ISSUE TITLE
immutable API

### ISSUE THREAD

**Issue by graingert** [mozilla-neutrino/webpack-chain#4]
It would be great to be able to create modules like:
```js
// Require the webpack-chain module. This module exports a single
// constructor function for creating a configuration API.
const config = require('webpack-chain/immutable');

// No need to instantiate, because config is already a root empty value.
// const config = new Config();

// Make configuration changes using the chain API.
// Every API call tracks a change to the stored configuration.

// Interact with entry points
const init = config
  .entry('index')
    .add('src/index.js')
    .end()
  // Modify output settings
  .output
    .path('dist')
    .filename('[name].bundle.js');

// Create named rules which can be modified later
const eslint = init.module
  .rule('lint')
    .test(/\.js$/)
    .pre()
    .include('src')
    // Even create named loaders for later modification
    .loader('eslint', 'eslint-loader', {
      rules: {
        semi: 'off'
      }
    });

const babel = eslint.module
  .rule('compile')
    .test(/\.js$/)
    .include('src', 'test')
    .loader('babel', 'babel-loader', {
      presets: [
        [require.resolve('babel-preset-es2015'), { modules: false }]
      ]
    });

// Create named plugins, too!

const plugins = babel
  .plugin('clean')
  .use(CleanPlugin, [BUILD], { root: CWD });

// Export the completed configuration object to be consumed by webpack
module.exports = babel.getConfig();
```

**Comment by eliperelman** [comment]
I love this idea, and really wanted something like this for v1, but unfortunately I didn't have the time to making it this way. I definitely want to consider this for v2.

**Comment by graingert** [comment]
@eliperelman it looks like it would be less code to use Immutable.js too. You'd get ChainableMap, ChainableSet for free.

**Comment by eliperelman** [comment]
At the moment keeping a running state of the configuration object is core to webpack-chain, so we won't be going this route right now. Closing for now, but would happily review a PR if someone is motivated.

**Comment by graingert** [comment]
You could still keep track of the state if it were immutable

**Comment by eliperelman** [comment]
@graingert how so? Let's say alpha.js has an instance of webpack-chain that is immutable:

```js
const beta = require('./beta');

const config = new Config();

config.set('a', 1);

beta(config);

console.log(config.toConfig());
```

beta.js

```js
module.exports = (config) => {
  config.set('b', 2);
};
```

How would that work if config state is immutable?

**Comment by graingert** [comment]
```js
const beta = require('./beta');

const config = new Config()
  .set('a', 1)
  |> beta;

console.log(config.toConfig()
```
Beta.js
```
module.exports = config => config.set('b', 2);
```

**Comment by graingert** [comment]
Beta will still have access to all the state in a

**Comment by eliperelman** [comment]
I want alpha to have access to the state set in beta as well as alpha.

**Comment by graingert** [comment]
@eliperelman it does, it's assigned to the config const

**Comment by eliperelman** [comment]
Sure, but that only works as long as all mutations are assigned to that single variable, right?

**Comment by graingert** [comment]
But there aren't any mutations?

**Comment by eliperelman** [comment]
So, I've been experimenting with using Immutable as the backing store for webpack-chain (very WIP, still missing functionality to convert to webpack config or smart merge data in):

https://github.com/mozilla-neutrino/webpack-chain/compare/immutable

To keep parity with the expected stateful API, by default a chain is initialized with `.asMutable()`. This should mean that you can drop into immutable mode simply by doing `chain.asImmutable()`.

@graingert I'd like to get your opinions on this direction, if you have time. 😃 

What I like about this is we get a whole lot of new methods to manipulate the collections, and should help with things like #25 and #28.

**Comment by graingert** [comment]
I think it would be better if asMutable worked with callbacks/transactions:


x.asMutable(v => {
    v.foo = 3;
})....

The asMutable method calls a function that can mutate the value as much as
it likes, but once synchronously completed commits the transaction to v.

**Comment by eliperelman** [comment]
My concern is the expectation of current users of Neutrino and webpack-chain. Right now the expectation is that every method call persists the state to the chain instance which you called against, e.g.

```js
const config = chain();

config.set('a', 1);
config.set('b', 2);

config // { a: 1, b: 2 }
```

This is a mutation against the chain instance held by config. While your statement could technically by correct that a transaction would be better, this is a completely different paradigm than what the API does right now. I think the expectation is that this API is mutable-first, with immutable as an option being entirely possible.

Maybe this could also be just a flag to chain (`chain() -> Mutable | chain(true) -> Immutable`)?

**Comment by graingert** [comment]
What about two APIs:

import Chain from 'chain/immutable';
import ChainMut from 'chain';

# you convert with copy constructors

const x = new Chain() ...;
const y = new ChainMut (x);

**Comment by eliperelman** [comment]
I think I can get behind something like that. The problem with `asMutable` and `asImmutable` is that they themselves mutate their reference, meaning a conversion from one to the other needs to use an interim copy method. I'll update my PR.

**Comment by graingert** [comment]
also I looked at https://facebook.github.io/immutable-js/#batching-mutations

I think withMutable would be the best api.

**Comment by eliperelman** [comment]
Trying to make this work introduces all sorts of problems. When putting the collection into "immutable-mode", every operation returns a new collection, and we lose the ability to chain with `.end()`. I'm not sure how reliably we can introduce an immutable-first API given that, unless we used Proxy to somehow trap calls to set and augment the new object with the chaining API. I guess it's possible, just may be a lot of work.

**Comment by graingert** [comment]
@eliperelman I don't think an immutable first API is necessarily required. I think it's safe at

```js
import Chain from 'chain/immutable';
```

**Comment by graingert** [comment]
@eliperelman not sure what you mean about being unable to chain .end()

Here's a version that users lodash/fp just for demo purposes:

```js
import _ from 'lodash/fp';

class Chain {
  constructor(path=[], v={}) {
    this._path = path;
    this._v = v;
  }

  entry(e) {
      return new Chain([...this._path, e], this._v);
  }

  set(p, v) {
      return new Chain(this._path, _.set([...this._path, p], v, this._v));
  }

  add(v) {
    function updater(w) {
        if (Array.isArray(w)) {
            return [...w, v]; 
        }
        if (w === undefined) {
            return [v];
        }
        throw new Error("Cannot append to object");
    }
    return new Chain(this._path, _.update(this._path, updater, this._v));
  }

  end() {
      return new Chain(_.initial(this._path), this._v);
  }

  value() {
    return this._v;
  }
}

const chain = new Chain()
  .entry('ham')
    .add('foo')
    .add('bar')
  .end()
  .entry('spam')
    .set('foo', 'bar')
    .set('baz', 'bacon')
  .end();


console.log(chain.value());
```

logs:
```js
{ ham: [ 'foo', 'bar' ], spam: { foo: 'bar', baz: 'bacon' } }
```

**Comment by eliperelman** [comment]
Closing for now until I have the motivation to get behind an immutable API again, or have a community PR to look at.
