### ISSUE TITLE
Remove rule.

### ISSUE THREAD

**Issue by gapipro** [mozilla-neutrino/webpack-chain#48]
I must be missing something, but how do you remove a rule from existing config?

**Comment by edmorley** [comment]
Hi! Is this for removing a loader entry within a rule, or removing the whole rule entry?

**Comment by gapipro** [comment]
Whole rule entry.

**Comment by eliperelman** [comment]
For rules it says:

`config.module.rules : ChainedMap`

https://github.com/mozilla-neutrino/webpack-chain#config-module-rules-shorthand-methods

A `ChainedMap` has a `delete` method: https://github.com/mozilla-neutrino/webpack-chain#chainedmap

So to remove a rule:

```js
config.module.rules.delete(ruleName)
```

**Comment by eliperelman** [comment]
Note that this is meant to be synonymous with the `Map#delete` method: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete

**Comment by eliperelman** [comment]
Closing as resolved. If my solution didn't work for you, please re-open. Thanks!

**Comment by JessicaSachs** [comment]
Hmmm. How do you do this under a nested `oneOf`?

I want something like this:
```
config.module.rule('less')
    .oneOf('normal')
    .delete('vue-style-loader')
```

The below _almost_ works, but fails because it leaves behind an empty object which blows up because it doesn't have a loader property.. How can I delete the whole thing?

```
config.module.rule('less')
    .oneOf('normal')
    .use('vue-style-loader')
    .loader('vue-style-loader')
    .clear();
```

**Comment by JessicaSachs** [comment]
:-(
I lamely replaced the entry with a Noop loader.
Let me know if there's a better way.

**Comment by eliperelman** [comment]
@JessicaSachs you should be able to delete with:

```js
config.module.rule('less').oneOfs.delete('vue-style-loader');
```

Let me know if that works for you.

**Comment by JessicaSachs** [comment]
Thanks for the response :-)

It doesn't work. It leaves the previous loader in there. Theoretically, if it did work, I would still wanna scope it inside of `config.module.rule('less').oneOf('normal')`.

**Comment by JessicaSachs** [comment]
This is the generated config I can inspect. I'm writing chained webpack ontop of this guy, so I don't really have a raw webpack.config.js to give you

[config.txt](https://github.com/neutrinojs/webpack-chain/files/2725706/config.txt)

**Comment by mixaDev** [comment]
```
config.module.rule('less')
	.oneOf('normal')
	.uses
	.delete('vue-style-loader')
```
