### ISSUE TITLE
has any hooks api to listen devserver or build ？

### ISSUE THREAD

**Issue by lichnow** [mozilla-neutrino/webpack-chain#74]
if I want to create or copy or delete some file to output dir, or do anything after dev-server started or webpack builded,how i can do?

**Comment by eliperelman** [comment]
If you want to take actions from the dev server, I believe this can be done with `before` or `setup`, depending on webpack version:

```js
config.devServer.before(/* ... */)
config.devServer.setup(/* ... */)
```

https://webpack.js.org/configuration/dev-server/#devserver-before
https://webpack.js.org/configuration/dev-server/#devserver-setup

Regarding taking action after webpack has done a build, this is something handled by the webpack core API specifically, not its configuration API.

https://webpack.js.org/api/node/

**Comment by lichnow** [comment]
@eliperelman sorry,i forget to read this in document,it ture,thx

**Comment by eliperelman** [comment]
No problem, good luck!

**Comment by chasegiunta** [comment]
FYI `before()` does not exist!
